version: "3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres

  migration:
    build: .
    command: python manage.py migrate
    volumes:
      - .:/code
    depends_on:
      - db
      
  running_tests:
    build: .
    command: python manage.py test
    volumes:
      - .:/code
    depends_on:
      - migration

  app:
    build:
      context: .
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - running_tests