# Generated by Django 2.2.7 on 2019-11-24 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', 'data_migration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ordered_pizzas',
        ),
        migrations.AddField(
            model_name='orderedpizza',
            name='order',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ordered_pizzas', to='api.Order'),
            preserve_default=False,
        ),
    ]
