# Generated by Django 2.2.7 on 2019-11-08 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', 'data_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverydetail',
            name='status',
            field=models.CharField(choices=[('not_ready', 'Not ready'), ('on_the_way', 'On the way'), ('delivered', 'Delivered')], default='not_ready', max_length=30),
        ),
    ]
