# Generated by Django 2.2.4 on 2019-11-10 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('assigned_courier_id', models.PositiveIntegerField(default=1, null=True)),
                ('status', models.CharField(choices=[('not_ready', 'Not ready'), ('on_the_way', 'On the way'), ('delivered', 'Delivered')], default='not_ready', max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PizzaFlavor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('s_size_price', models.PositiveSmallIntegerField(null=True)),
                ('m_size_price', models.PositiveSmallIntegerField(null=True)),
                ('l_size_price', models.PositiveSmallIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderedPizza',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('size', models.CharField(choices=[('s', 'Small'), ('m', 'Medium'), ('l', 'Large')], max_length=1)),
                ('count', models.PositiveSmallIntegerField(default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('pizza_flavor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.PizzaFlavor')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_id', models.PositiveIntegerField(default=1)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_paid', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('delivery_detail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.DeliveryDetail')),
                ('ordered_pizzas', models.ManyToManyField(to='api.OrderedPizza')),
            ],
        ),
    ]
