# Generated by Django 2.2.7 on 2019-11-06 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizzaflavor',
            name='id',
        ),
        migrations.AddField(
            model_name='pizzaflavor',
            name='code',
            field=models.CharField(default=None, max_length=10, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
