# Generated by Django 2.2.7 on 2019-11-08 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_auto_20191108_2234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverydetail',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='orderedpizza',
            name='last_updated',
        ),
    ]
