# Generated by Django 2.2.7 on 2019-11-08 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20191108_2257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizzaflavor',
            name='code',
        ),
        migrations.AddField(
            model_name='pizzaflavor',
            name='id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
