# Generated by Django 2.2.7 on 2019-11-06 20:23
from django.db import migrations
from api.models import PizzaFlavor

def insert_pizza_flavors(apps, schema_editor):

    pizza_flavors_to_insert = [
        {
            'code': 'peppe',
            'name': 'Pepperoni',
            's_size_price': 5,
            'm_size_price': 8,
            'l_size_price': 10
        },
        {
            'code': 'marga',
            'name': 'Margarita',
            's_size_price': 3,
            'm_size_price': 5,
            'l_size_price': 8
        },
        {
            'code': 'neap',
            'name': 'Neapolitan',
            's_size_price': 7,
            'm_size_price': 9,
            'l_size_price': 11
        }
    ]

    for pizza_flavor_to_insert in pizza_flavors_to_insert:
        PizzaFlavor.objects.create(
            **pizza_flavor_to_insert
        )

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20191106_2321'),
    ]

    operations = [
        migrations.RunPython(insert_pizza_flavors),
    ]
